[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"
# timeout = 30  # This line caused the build error.
memory = 1024

[[redirects]]
from = "/api/transcribe"
to = "/.netlify/functions/transcribe-audio"
status = 200

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/chat-completion"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Max-Age = "86400"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "microphone=(), camera=(), geolocation=(), interest-cohort=()"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
