[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Redirects for new API endpoints
[[redirects]]
  from = "/api/transcribe"
  to = "/.netlify/functions/transcribe-audio"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat-completion"
  status = 200

# Legacy redirect cleanup (remove old AssemblyAI endpoint)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# CORS headers for API endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"

# Security headers for the main site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "microphone=(), camera=(), geolocation=(), interest-cohort=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for functions (these need to be set in Netlify UI)
# Required:
# - OPENAI_API_KEY
# - ELEVEN_LABS_API_KEY (if using server-side Eleven Labs calls)

# Build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Function settings
[functions]
  # Increase timeout for audio processing
  timeout = 30
  # Set memory limit for audio file handling
  memory = 1024